-- Drop Tables.


DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT_ROLE_MAPPING_HISTORY CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT_STATUS CASCADE CONSTRAINTS;
DROP TABLE AUTHENTICATION_CONFIG CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE OXYGEN_CYLINDER_DETAILS CASCADE CONSTRAINTS;
DROP TABLE OXYGEN_CYLINDER_PLANT CASCADE CONSTRAINTS;
DROP TABLE PASSWORD CASCADE CONSTRAINTS;
DROP TABLE PATIENT_DETAILS CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_METHOD CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_STATUS CASCADE CONSTRAINTS;
DROP TABLE PERMISSIONS CASCADE CONSTRAINTS;
DROP TABLE RENTAL_PRICE CASCADE CONSTRAINTS;
DROP TABLE RENTER_PAYMENT_CHECKOUT CASCADE CONSTRAINTS;
DROP TABLE ROLE CASCADE CONSTRAINTS;
